export const SAVE_COMMENT='SAVE_COMMENT';

export const FETCH_COMMENTS='FETCH_COMMENTS';
export const FETCH_COMMENTS_SUCCESS='FETCH_COMMENTS_SUCCESS';
export const FETCH_COMMENTS_FAIL='FETCH_COMMENTS_FAIL';